Repository googleapis/nodejs-bigtable, pull requests merged in 2018-06, with the labels that each got.

#150 Updated with missing documentation
  src/chunktransformer.js
  src/cluster.js
  src/family.js
  src/filter.js
  src/instance.js
  src/mutation.js
  src/table.js
Labels: cla: yes

#159 Drop support for nodev4.
  .circleci/config.yml
  package.json
Labels: cla: yes

#160 Drop node4 completely
  .circleci/config.yml
  samples/package-lock.json
Labels: cla: yes

#162 Convert common js patterns to use node-v6 capabilities.
  src/app-profile.js
  src/chunktransformer.js
  src/cluster.js
  src/family.js
  src/index.js
  src/instance.js
  src/table.js
  test/chunktransformer.js
  test/index.js
  test/instance.js
  test/table.js
Labels: cla: yes

#139 Quickstart, table / column family admin samples
  .eslintignore
  README.md
  samples/README.md
  samples/package.json
  samples/quickstart.js
  samples/system-test/quickstart.test.js
  samples/tableadmin.js
Labels: cla: yes

#170 Fix samples system tests
  samples/instances.js
  samples/package.json
  samples/system-test/instances.test.js
Labels: cla: yes

#158 Switch src/ to use ES classes
  samples/system-test/instances.test.js
  src/app-profile.js
  src/chunktransformer.js
  src/cluster.js
  src/family.js
  src/filter.js
  src/index.js
  src/instance.js
  src/mutation.js
  src/row.js
  src/table.js
  test/index.js
Labels: cla: yes

#174 Issue#137 name vs id fix for instance.js
  src/app-profile.js
  src/cluster.js
  src/instance.js
  src/table.js
  test/app-profile.js
  test/cluster.js
  test/instance.js
  test/table.js
Labels: cla: yes

#173 Fixing docs that refered to "Compute Instances"
  src/index.js
  src/instance.js
Labels: cla: yes, type: docs

#168 resolved name-vs-id issue for table.js
  src/family.js
  src/instance.js
  src/row.js
  src/table.js
  system-test/bigtable.js
  test/family.js
  test/index.js
  test/instance.js
  test/row.js
  test/table.js
Labels: Breaking Change, cla: yes

#169 switch id and name in app-profile
  src/app-profile.js
  src/instance.js
  system-test/bigtable.js
  test/app-profile.js
  test/instance.js
Labels: cla: yes

#161 Allow raw table mutations.
  src/table.js
  test/table.js
Labels: Breaking Change, cla: yes

#167 Fix for Issue 117, setMetadata to use partialInstance Update
  src/instance.js
  test/instance.js
Labels: cla: yes

#172 change id vs. name in Cluster
  samples/instances.js
  src/app-profile.js
  src/cluster.js
  src/index.js
  src/instance.js
  test/app-profile.js
  test/cluster.js
  test/index.js
  test/instance.js
Labels: Breaking Change, cla: yes

#183 system tests fixes
  src/cluster.js
  system-test/bigtable.js
  test/cluster.js
Labels: cla: yes

#184 instance id/name swap in src/test index.js
  src/index.js
  test/index.js
Labels: cla: yes

#180 Cleanup
  src/app-profile.js
  src/chunktransformer.js
  src/cluster.js
  src/family.js
  src/filter.js
  src/index.js
  src/instance.js
  src/mutation.js
  src/row.js
  src/table.js
  test/filter.js
Labels: cla: yes

#187 Handle non utf8 buffer filters
  package.json
  src/filter.js
  test/filter.js
Labels: cla: yes

#191 Fix sample/system-test: Change name to id in sample system test
  samples/system-test/instances.test.js
Labels: cla: yes

#188 Remove id<->name check for cluster since its not done anywhere else
  src/cluster.js
Labels: cla: yes

#192 Updating README snippet
  README.md
Labels: cla: yes

#186 resolved name vs. id issue for family.js
  src/family.js
  src/table.js
  system-test/bigtable.js
  test/family.js
  test/table.js
Labels: Breaking Change, cla: yes

#195 Fix bad encoded filter
  src/filter.js
  test/filter.js
Labels: cla: yes

#197 New errors for name / id checks in Instance constructors
  src/app-profile.js
  src/cluster.js
  src/index.js
  src/instance.js
  src/table.js
  test/app-profile.js
  test/cluster.js
  test/instance.js
  test/table.js
Labels: cla: yes

#209 typo fix for apidoc comment
  src/index.js
  src/instance.js
Labels: cla: yes

#208 fix #196 should not call replaceProjectID token when projectid is passed in option
  src/index.js
  test/index.js
Labels: cla: yes

#202 New errors for name / id checks in family constructor
  src/family.js
  src/table.js
  test/family.js
  test/table.js
Labels: cla: yes

#203 Fix rowKey being force stringified to utf8
  src/chunktransformer.js
  src/mutation.js
  src/table.js
  test/chunktransformer.js
  test/mutation.js
  test/row.js
Labels: cla: yes

#212 chore: weed the lock file
  samples/package-lock.json
Labels: cla: yes

#214 fix: drop repo-tools as an exec wrapper
  .circleci/config.yml
  package.json
  samples/package.json
Labels: cla: yes

#213 update gax dependency
  package-lock.json
  package.json
  protos/google/bigtable/v2/bigtable.proto
  protos/google/bigtable/v2/data.proto
  samples/package-lock.json
  src/index.js
  src/v2/bigtable_client.js
  src/v2/bigtable_instance_admin_client.js
  src/v2/bigtable_table_admin_client.js
  src/v2/doc/google/bigtable/v2/doc_bigtable.js
  synth.py
  test/index.js
Labels: cla: yes

#82 added waitForReplication method to implement consistency-token check
  src/table.js
  system-test/bigtable.js
  test/table.js
Labels: cla: yes

#207 Delete data on row.js mutation calls
  src/row.js
  test/row.js
Labels: cla: yes

#223 Updating the Readme: Node is now beta
  .cloud-repo-tools.json
  README.md
Labels: cla: yes, type: docs

#226 refactor(build): use `npm ci` in synth script
  synth.py
Labels: cla: yes

#228 fix: fix sinon sandbox warnings
  test/chunktransformer.js
  test/filter.js
  test/index.js
  test/mutation.js
  test/row.js
  test/table.js
Labels: cla: yes

#227 fix(deps): drop dependency on @google-cloud/common
  package-lock.json
  package.json
  src/app-profile.js
  src/cluster.js
  src/family.js
  src/index.js
  src/instance.js
  src/row.js
  src/table.js
  test/app-profile.js
  test/cluster.js
  test/family.js
  test/index.js
  test/instance.js
  test/row.js
  test/table.js
Labels: cla: yes

#230 fix(dep): drop dependency on safe-buffer
  package.json
  src/mutation.js
  test/mutation.js
Labels: cla: yes

#231 fix(deps): remove dependency on string-format-obj
  test/app-profile.js
  test/cluster.js
  test/family.js
  test/instance.js
Labels: cla: yes

#232 Changing test "var" to "const" and "let"
  test/app-profile.js
  test/cluster.js
  test/family.js
  test/filter.js
  test/index.js
  test/instance.js
  test/mutation.js
  test/row.js
  test/table.js
Labels: cla: yes

#233 Allow creating a Bigtable instance without the new keyword.
  src/index.js
  test/index.js
Labels: cla: yes, in progress

#225 0.15.0
  .circleci/config.yml
  package-lock.json
  package.json
  samples/package-lock.json
  samples/package.json
Labels: cla: yes, in progress
