Repository googleapis/nodejs-bigtable, pull requests merged in 2018-03, with the labels that each got.

#59 Fix error with broken mutate-rows test
  src/table.js
  system-test/mutate-rows.js
  test/table.js
Labels: cla: no, cla: yes

#60 Fixing a lint regression
  test/table.js
Labels: cla: yes

#35 Convert to GAPIC
  package.json
  src/cluster.js
  src/family.js
  src/index.js
  src/instance.js
  src/row.js
  src/table.js
  system-test/bigtable.js
  system-test/mutate-rows.js
  system-test/read-rows-acceptance-tests.js
  system-test/read-rows.js
  test/cluster.js
  test/family.js
  test/filter.js
  test/index.js
  test/instance.js
  test/row.js
  test/table.js
Labels: cla: yes

#46 Improve transform perf
  src/chunktransformer.js
  src/mutation.js
  src/row.js
  test/mutation.js
  test/row.js
Labels: cla: yes

#64 Fix read retires.
  src/chunktransformer.js
  src/table.js
  system-test/data/read-rows-retry-test.json
  system-test/read-rows.js
  test/table.js
Labels: cla: yes

#48 fix#47 Respect decode: false option when cell value is split between chunks
  src/chunktransformer.js
  test/chunktransformer.js
Labels: cla: no

#66 v0.13.0
  package.json
Labels: cla: no, cla: yes

#68 chore: setup nighty build in CircleCI
  .circleci/config.yml
  .circleci/get_workflow_name.py
Labels: cla: yes

#69 chore: make samples depend on the current version
  samples/package.json
Labels: cla: yes

#63 Upgrade repo-tools and regenerate scaffolding.
  .github/ISSUE_TEMPLATE.md
  .gitignore
  CONTRIBUTORS
  README.md
  package-lock.json
  package.json
  samples/README.md
  samples/package-lock.json
  samples/package.json
Labels: cla: no, cla: yes

#72 chore: workaround for repo-tools EPERM
  .circleci/config.yml
Labels: cla: yes

#73 chore: one more workaround for repo-tools EPERM
  .circleci/config.yml
Labels: cla: yes
