Repository googleapis/nodejs-bigtable, pull requests merged in 2019-06, with the labels that each got.

#492 docs(samples): add conditional, batch, and incremental write samples
  samples/package.json
  samples/system-test/write.js
  samples/writeBatch.js
  samples/writeConditionally.js
  samples/writeIncrement.js
  samples/writeSimple.js
Labels: cla: yes

#493 docs(samples): clean up 'write conditionally' samples
  samples/writeConditionally.js
Labels: cla: yes

#494 build: remove unused clang format
  .clang-format
  samples/writeBatch.js
  src/app-profile.ts
  src/instance.ts
Labels: automerge, cla: yes

#495 chore(deps): update dev dependency p-queue to ^6.0.2
  package.json
  system-test/bigtable.ts
Labels: cla: yes

#497 chore(deps): update dependency typescript to ~3.5.0
  package.json
  test/index.ts
  test/table.ts
Labels: cla: yes

#499 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#498 fix: "requires_billing " should be "requires_billing"
  .repo-metadata.json
Labels: cla: yes

#500 feat: support apiEndpoint override
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  README.md
  samples/README.md
  src/v2/bigtable_client.js
  src/v2/doc/google/bigtable/v2/doc_bigtable.js
  src/v2/doc/google/bigtable/v2/doc_data.js
  src/v2/doc/google/protobuf/doc_any.js
  src/v2/doc/google/protobuf/doc_wrappers.js
  synth.metadata
  test/gapic-v2.js
Labels: cla: yes

#485 feat: update the admin APIs
  package.json
  protos/google/bigtable/admin/v2/bigtable_instance_admin.proto
  protos/google/bigtable/admin/v2/bigtable_table_admin.proto
  protos/google/bigtable/admin/v2/common.proto
  protos/google/bigtable/admin/v2/instance.proto
  protos/google/bigtable/admin/v2/table.proto
  src/index.ts
  src/v2/bigtable_instance_admin_client.js
  src/v2/bigtable_instance_admin_client_config.json
  src/v2/bigtable_table_admin_client.js
  src/v2/bigtable_table_admin_client_config.json
  src/v2/doc/google/bigtable/admin/v2/doc_bigtable_instance_admin.js
  src/v2/doc/google/bigtable/admin/v2/doc_bigtable_table_admin.js
  src/v2/doc/google/bigtable/admin/v2/doc_instance.js
  src/v2/doc/google/bigtable/admin/v2/doc_table.js
  src/v2/doc/google/iam/v1/doc_iam_policy.js
  src/v2/doc/google/iam/v1/doc_policy.js
  src/v2/doc/google/longrunning/doc_operations.js
  src/v2/doc/google/protobuf/doc_duration.js
  src/v2/doc/google/protobuf/doc_empty.js
  src/v2/doc/google/protobuf/doc_field_mask.js
  src/v2/doc/google/protobuf/doc_timestamp.js
  src/v2/doc/google/type/doc_expr.js
  synth.metadata
  synth.py
  test/gapic-v2.js
Labels: :rotating_light:, cla: yes

#501 refactor: drop dependency on nodejs-repo-tools
  .cloud-repo-tools.json
  README.md
  package.json
  samples/README.md
  samples/package.json
  samples/quickstart.js
  samples/tableadmin.js
  samples/test/.eslintrc.yml
  samples/test/app-profile.js
  samples/test/cluster.js
  samples/test/family.js
  samples/test/instance.js
  samples/test/instances.test.js
  samples/test/row.js
  samples/test/table.js
  samples/test/write.js
  samples/writeBatch.js
  samples/writeConditionally.js
  samples/writeIncrement.js
  samples/writeSimple.js
Labels: cla: yes

#484 chore: release 2.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: :rotating_light:, autorelease: pending, cla: yes, type: process

#502 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#503 chore: release 2.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#504 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
