Repository googleapis/nodejs-bigtable, pull requests merged in 2019-02, with the labels that each got.

#409 Release @google-cloud/bigtable v1.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#411 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#413 chore: move CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: cla: yes

#414 docs: update contributing path in README
  README.md
Labels: cla: yes

#415 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes

#416 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#418 fix: throw on invalid credentials
  src/v2/bigtable_client.js
  synth.metadata
Labels: cla: yes

#421 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#422 Region tag consistency
  samples/hello-world/index.js
Labels: cla: yes, type: cleanup

#419 build: use linkinator for docs test
  package.json
Labels: cla: yes

#424 chore: update proto formatting
  protos/google/bigtable/v2/bigtable.proto
  protos/google/bigtable/v2/data.proto
  src/v2/doc/google/rpc/doc_status.js
  synth.metadata
Labels: cla: yes
