Repository googleapis/nodejs-bigtable, pull requests merged in 2020-05, with the labels that each got.

#724 feat: check status of long running operation by its name
  protos/protos.js
  src/v2/bigtable_instance_admin_client.ts
  src/v2/bigtable_table_admin_client.ts
  synth.metadata
  test/gapic_bigtable_instance_admin_v2.ts
  test/gapic_bigtable_table_admin_v2.ts
  test/gapic_bigtable_v2.ts
Labels: automerge, cla: yes

#726 Create CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#725 fix: UpdateBackupRequest.backup is a resource, not a resource reference - remove annotation
  protos/google/bigtable/admin/v2/bigtable_table_admin.proto
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#727 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#728 feat: Cloud functions example for Bigtable
  package.json
  samples/functions/index.js
  samples/functions/package.json
  samples/package.json
  samples/readSnippets.js
  samples/test/functions.js
Labels: cla: yes

#729 build: point to team in correct org
  .github/CODEOWNERS
Labels: cla: yes

#733 fix(types): stricter types are now enforced
  src/instance.ts
Labels: cla: yes
