Repository googleapis/nodejs-bigtable, pull requests merged in 2020-09, with the labels that each got.

#795 feat: getAppProfilesStream emits (if there are any failed locations present) decorated error with failedLocations info
  src/index.ts
  src/instance.ts
  test/index.ts
  test/instance.ts
Labels: api: bigtable, cla: yes

#794 Introduce Backups
  package.json
  src/backup.ts
  src/cluster.ts
  src/index.ts
  src/instance.ts
  src/table.ts
  system-test/bigtable.ts
  test/backup.ts
  test/cluster.ts
  test/index.ts
  test/instance.ts
  test/table.ts
Labels: api: bigtable, cla: yes

#787 chore: remove use of retry-request in favor of gax stream
  package.json
  src/index.ts
  src/table.ts
  system-test/mutate-rows.ts
  test/index.ts
  test/table.ts
Labels: api: bigtable, cla: yes

#798 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#801 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: api: bigtable, cla: yes

#800 docs: add Backup samples
  samples/backups.create.js
  samples/backups.delete.js
  samples/backups.get.js
  samples/backups.list.js
  samples/backups.restore.js
  samples/backups.update.js
  samples/test/backups.js
  samples/test/util.js
  src/backup.ts
  src/cluster.ts
  src/instance.ts
Labels: api: bigtable, cla: yes, samples

#802 docs: update list of available samples
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none
