Repository googleapis/nodejs-bigtable, pull requests merged in 2020-08, with the labels that each got.

#781 fix: respect pageSize and pageToken from gaxOptions
  src/instance.ts
  src/table.ts
  test/instance.ts
Labels: cla: yes

#783 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#784 build: use gapic-generator-typescript v1.0.7.
  src/v2/bigtable_client.ts
  src/v2/bigtable_instance_admin_client.ts
  src/v2/bigtable_table_admin_client.ts
  synth.metadata
Labels: automerge, cla: yes, context: full

#785 chore: update cloud rad kokoro build job
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#786 build: perform publish using Node 12
  .kokoro/release/publish.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#788 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#790 docs(types): improve filter config options types
  src/row.ts
Labels: api: bigtable, cla: yes

#792 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
