Repository googleapis/nodejs-bigtable, pull requests merged in 2020-07, with the labels that each got.

#752 docs: improve jsdocs
  src/index.ts
Labels: cla: yes

#753 build: use bazel build
  package.json
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#754 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#759 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#763 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#764 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#765 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: partial

#769 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#768 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#772 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#770 feat: remove through2 dependency
  package.json
  src/table.ts
  system-test/read-rows-acceptance-test.json
Labels: cla: yes

#773 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#775 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#762 chore: remove paginator dependency and use gapic to return streams for paginated calls instead
  package.json
  src/index.ts
  src/instance.ts
  system-test/bigtable.ts
  test/index.ts
  test/instance.ts
Labels: cla: yes

#771 feat: add gapic getAppProfilesStream method
  src/index.ts
  src/instance.ts
  system-test/bigtable.ts
  test/index.ts
  test/instance.ts
Labels: cla: yes

#776 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#777 chore: update promisifyAll exclude
  src/instance.ts
  test/instance.ts
Labels: cla: yes

#778 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#780 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
