Repository googleapis/nodejs-bigtable, pull requests merged in 2020-06, with the labels that each got.

#736 build: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#740 feat(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v2/bigtable_client.ts
  src/v2/bigtable_instance_admin_client.ts
  src/v2/bigtable_table_admin_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#742 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#745 fix: handle fallback option properly
  src/v2/bigtable_client.ts
  src/v2/bigtable_instance_admin_client.ts
  src/v2/bigtable_table_admin_client.ts
  synth.metadata
Labels: cla: yes, context: none

#720 fix(types)!: improve types in index.ts
  src/cluster.ts
  src/index.ts
  src/instance.ts
  system-test/bigtable.ts
  test/cluster.ts
  test/index.ts
  test/instance.ts
Labels: cla: yes

#746 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#747 feat: update bigtable grpc service config
  protos/google/bigtable/admin/v2/bigtable_instance_admin.proto
  protos/google/bigtable/admin/v2/bigtable_table_admin.proto
  protos/google/bigtable/admin/v2/common.proto
  protos/google/bigtable/admin/v2/instance.proto
  protos/google/bigtable/admin/v2/table.proto
  protos/google/bigtable/v2/bigtable.proto
  protos/google/bigtable/v2/data.proto
  protos/protos.json
  src/v2/bigtable_client_config.json
  synth.metadata
Labels: cla: yes, context: full

#744 docs(samples): Update region tags for reads and filters
  samples/filterSnippets.js
  samples/readSnippets.js
Labels: cla: yes

#751 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
