Repository googleapis/nodejs-bigtable, pull requests merged in 2021-01, with the labels that each got.

#832 chore: update license headers
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  src/v2/bigtable_client.ts
  src/v2/bigtable_instance_admin_client.ts
  src/v2/bigtable_table_admin_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_bigtable_instance_admin_v2.ts
  test/gapic_bigtable_table_admin_v2.ts
  test/gapic_bigtable_v2.ts
Labels: api: bigtable, cla: yes, context: none

#834 fix: Renaming region tags to not conflict with documentation snippets
  README.md
  linkinator.config.json
  package.json
  samples/README.md
  samples/api-reference-doc-snippets/.eslintrc.yml
  samples/api-reference-doc-snippets/app-profile.js
  samples/api-reference-doc-snippets/backups.create.js
  samples/api-reference-doc-snippets/backups.delete.js
  samples/api-reference-doc-snippets/backups.get.js
  samples/api-reference-doc-snippets/backups.list.js
  samples/api-reference-doc-snippets/backups.restore.js
  samples/api-reference-doc-snippets/backups.update.js
  samples/api-reference-doc-snippets/cluster.js
  samples/api-reference-doc-snippets/family.js
  samples/api-reference-doc-snippets/instance.js
  samples/api-reference-doc-snippets/row.js
  samples/api-reference-doc-snippets/table.js
  samples/package.json
  src/app-profile.ts
  src/backup.ts
  src/cluster.ts
  src/family.ts
  src/instance.ts
  src/row.ts
  src/table.ts
Labels: api: bigtable, cla: yes

#833 feat: introduce style enumeration
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: none

#835 docs: remove samples listed in subfolder
  README.md
  linkinator.config.json
  samples/README.md
  synth.metadata
Labels: api: bigtable, cla: yes, context: none

#838 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#836 fix: set keepalive configuration
  src/index.ts
  test/index.ts
Labels: api: bigtable, automerge, cla: yes
