Repository googleapis/nodejs-bigtable, pull requests merged in 2022-01, with the labels that each got.

#968 chore: add api_shortname and library_type to repo metadata
  .repo-metadata.json
  README.md
Labels: api: bigtable

#980 fix: fix retry logic in mutate and read
  src/table.ts
  test/table.ts
Labels: automerge, api: bigtable

#952 docs: stop publishing autogenerated gapic and protobuf docs
  .jsdoc.js
Labels: cla: yes, api: bigtable

#986 fix: add close() in the wrapper
  src/index.ts
Labels: api: bigtable

#992 test: add test for close()
  test/index.ts
Labels: automerge, api: bigtable
