Repository googleapis/nodejs-bigtable, pull requests merged in 2023-05, with the labels that each got.

#1283 test: Make the mock server test async
  test/errors.ts
Labels: api: bigtable, size: s

#1282 test: test ReadRows logic with local gRPC server
  test/readrows.ts
  test/utils/readRowsImpl.ts
Labels: automerge, api: bigtable, size: l

#1285 test: skip failing Windows test
  test/mutation.ts
Labels: api: bigtable, size: xs

#1277 fix: Parsing for qualifiers with colon characters
  src/mutation.ts
  test/mutation.ts
Labels: kokoro:run, api: bigtable, size: s

#1284 fix: properly handle asynchronous read from stream
  src/chunktransformer.ts
  src/table.ts
  test/chunktransformer.ts
  test/readrows.ts
Labels: api: bigtable, size: m
