Repository googleapis/nodejs-bigtable, pull requests merged in 2024-12, with the labels that each got.

#1521 fix: Address assertion error in TestReadRows_Retry_LastScannedRow conformance test
  src/chunktransformer.ts
  src/tabular-api-surface.ts
  testproxy/known_failures.txt
Labels: automerge, api: bigtable, size: m

#1524 fix: Fix TestReadRows_Generic_CloseClient conformance test by passing grpc status codes for closed client errors
  src/tabular-api-surface.ts
  testproxy/known_failures.txt
Labels: automerge, api: bigtable, size: s

#1532 test: Prepare helper function for readWriteModifyRow test proxy service - replica
  test/test-proxy/readModifyWriteRow.ts
  testproxy/services/utils/request/readModifyWriteRow.ts
Labels: api: bigtable, size: m

#1535 chore(testproxy): Change the readModifyWriteRow test proxy so that it uses the handwritten layer
  test/test-proxy/readModifyWriteRowService.ts
  testproxy/known_failures.txt
  testproxy/services/read-modify-write-row.js
Labels: api: bigtable, size: m

#1537 chore(testproxy): Fix the test proxy so that TestReadModifyWriteRow_NoRetry_TransientError passes
  testproxy/known_failures.txt
  testproxy/services/read-modify-write-row.js
Labels: api: bigtable, size: s

#1538 test: Sleep on copy backup system tests to avoid quota issues
  system-test/bigtable.ts
Labels: api: bigtable, size: xs

#1533 chore(testproxy): Address the TestReadRows_Generic_DeadlineExceeded test
  src/tabular-api-surface.ts
  test/table.ts
  testproxy/known_failures.txt
  testproxy/services/create-client.js
  testproxy/services/read-rows.js
Labels: api: bigtable, size: m

#1542 chore(testproxy): Address the TestReadModifyWriteRow_Generic_Headers test
  testproxy/known_failures.txt
  testproxy/services/read-modify-write-row.js
Labels: api: bigtable, size: xs

#1545 chore: make post-processor optional
  owlbot.py
Labels: automerge, api: bigtable, size: xs

#1546 chore(testproxy): Address the TestReadRows_Retry_StreamReset test
  testproxy/known_failures.txt
Labels: api: bigtable, size: xs

#1543 chore(testproxy): Address the TestReadModifyWriteRow_Generic_DeadlineExceeded conformance test
  testproxy/known_failures.txt
  testproxy/services/create-client.js
Labels: api: bigtable, size: s

#1549 fix: Update owlbot.py to exculde sync repo
  .github/sync-repo-settings.yaml
  owlbot.py
Labels: automerge, api: bigtable, size: xs

#1539 fix: Paused scan test is now fixed
  testproxy/index.js
  testproxy/known_failures.txt
Labels: automerge, api: bigtable, size: xs

#1551 fix: Check and mutate generic header conformance test
  testproxy/known_failures.txt
  testproxy/services/check-and-mutate-row.js
Labels: automerge, api: bigtable, size: xs

#1541 chore(testproxy): Change the checkAndMutateRow test proxy service so that it uses the handwritten layer
  test/mutation.ts
  test/test-proxy/checkAndMutateRowService.ts
  test/test-proxy/mutationParseInverse.ts
  test/test-proxy/readModifyWriteRowService.ts
  testproxy/known_failures.txt
  testproxy/services/check-and-mutate-row.js
  testproxy/services/utils/request/createFlatMutationsList.ts
  testproxy/services/utils/request/mutateInverse.ts
  tsconfig.json
Labels: api: bigtable, size: l

#1554 chore(testproxy): Address the TestMutateRows_Generic_DeadlineExceeded conformance test
  src/tabular-api-surface.ts
  test/table.ts
  testproxy/known_failures.txt
  testproxy/services/bulk-mutate-rows.js
Labels: api: bigtable, size: m

#1557 chore(testproxy): Remove TestCheckAndMutateRow_Generic_Headers from known failures
  testproxy/known_failures.txt
Labels: automerge, api: bigtable, size: xs

#1556 chore(testproxy): Address the CheckAndMutateRow_Generic_CloseClient conformance test
  testproxy/known_failures.txt
  testproxy/services/check-and-mutate-row.js
Labels: automerge, api: bigtable, size: xs

#1560 chore(testproxy): Remove multiple known failures that have already been addressed
  testproxy/known_failures.txt
Labels: api: bigtable, size: xs
