Repository googleapis/nodejs-bigtable, pull requests merged in 2025-01, with the labels that each got.

#1561 chore(testproxy): Address TestCheckAndMutateRow_NoRetry_TrueMutations and TestCheckAndMutateRow_NoRetry_FalseMutations conformance tests
  test/test-proxy/checkAndMutateRowService.ts
  testproxy/known_failures.txt
  testproxy/services/check-and-mutate-row.js
Labels: api: bigtable, size: s

#1562 fix: Conformance test sample rowkeys generic deadline
  src/tabular-api-surface.ts
  testproxy/known_failures.txt
  testproxy/services/sample-row-keys.js
  testproxy/services/utils/request/sampleRowKeys.ts
Labels: api: bigtable, samples, size: m

#1564 chore: Common pitfalls unit test
  test/readrows.ts
  test/utils/readRowsImpl.ts
  test/utils/readRowsServiceParameters.ts
Labels: automerge, api: bigtable, size: m

#1567 chore(testproxy): Update known failures
  .github/workflows/mandatory-conformance.yaml
  testproxy/known_failures.txt
Labels: api: bigtable, size: xs

#1563 fix: Use the universe domain if it is provided by the user
  src/index.ts
  system-test/service-path.ts
Labels: automerge, api: bigtable, size: m
